### ISSUE TITLE
Horion 1.13.0 Bug List

### ISSUE THREAD

**Issue by Zelqx** [horionclient/Horion#128] opened 2019-11-03 09:55 UTC
# Horion 1.13.0 Bug List
###  When a tick is provided that means the bug has been patched

- [x] When Blink is on, Nofall doesnt work.
- [x] Inventory Move 
- [x] freecam
- [x] Auto Armour
- [x] Step wont let you move when you crouch
- [x] Chest Aura
- [x] .enchant
- [x] Stackable Item
- [x] .give
- [x] Aimbot required click does not work
- [x] .dupe
- [x] Trigger bot - Doesnt work on players and does hit mobs
- [x] Air Jump
- [x] Air Swim
- [x] Bhop
- [x] Click TP
- [x] Xray doesnt reveal torches and chests/e-chests and furnaces and crafting tables after the fix.
- [x] Xray 
- [x] .SetOffHand
- [x] AntiBot - makes ESP Grey
- [x] Make .damage turn off no fall automaticly to damage you
- [x] Fly takes you to gamemode c instead of staying into original gamemode
- [x] Glide Bug https://youtu.be/D9KUyqugDqk (read description)
- [x] Add back the fonts lmao. gamer font too sharp for us to read
- [x] Chest Stealer
- [x] When getting off of a rideable animal your game will crash
- [x] When in gamemode c, and fly is turned off and on. You are unable to fly
- [x] When in freecam, you can take fall damage (which you arent supposed to)
- [x] Reach Does not work
- [x] .give/.soh (item name) is kinda glitched out.for example when doing .give wood 1 or .give stone 
       1, it doesnt work
- [x] Criticals does not work. ive tested it with 2 zombies, both took 20 hits to kill with fist. Crits on 
       and off
- [x] if you go to mineplex and try to auto enchant it crashes you
- [x] Xray is bugged when holding barriers (https://youtu.be/lZD6mNvEyG8)
- [x] freecam and blink dont work on realms
- [x] .give (item name (Not item number!)) wont let you get specific data value https://youtu.be/UZL72JLV1t0 (read desc) .give ((item *name* 1 7) doesnt give the color i want.))
- [ ] Criticals has problems with NoFall - You'll kinda randomly get fall damage and die from it
- [x] When clicking on module on the new array list, it doesnt turn off the module
- [ ] fasteat
- [ ] autoclicker right click does not work for bottle of enchantings
- [ ] stackable item hack does not work on bucket items
- [x] gamerskin doesnt work (please message me if im wrong)
- [ ] when midclicking people. everyone (mobs and animals and other players) turn green.
you cant turn it off to remove the green if you have people added already..  only if nofriends is on, it fixes it.
- [x ] nuker does not work with tools

 Credit to Sιɳ#0768 For a few of the bugs
 please contact me on discord if you have trouble understanding : Zelqx#0001

(just want to say thank you for all the work you put in horion 1.13, its amazing! ill be looking forward to future updates :D)

Captures:
Midclick bug - http://prntscr.com/pxn1n9

**Comment by Damakermiddle** [comment] 2019-11-03 19:04
.cords don't work either

**Comment by imfuckingtoasted** [comment] 2019-11-03 19:10
.dupe not working

**Comment by Damakermiddle** [comment] 2019-11-03 19:11
^^Since .give works(uses the same way, nopacket), it will be fixed soon

**Comment by Zelqx** [comment] 2019-11-03 19:14
.coords works

**Comment by carloslol109** [comment] 2019-11-03 19:22
Whenever I inject my game just crashes what is that?

**Comment by Damakermiddle** [comment] 2019-11-03 20:28
.-. go learn how to code

**Comment by Kiffolisk** [comment] 2019-11-03 20:28
jetpack lags and i hate it

**Comment by Damakermiddle** [comment] 2019-11-03 20:47
its working fine, u have bypass on??

**Comment by Zelqx** [comment] 2019-11-03 20:49
xd

**Comment by Zelqx** [comment] 2019-11-03 20:50
try to keep this on the Discord instead

**Comment by Zelqx** [comment] 2019-11-03 21:22
.give doesnt not work, but they fixed the issue when it crashed your game.

**Comment by Zelqx** [comment] 2019-11-05 23:30
AirJump Does not work :?

**Comment by RestudyXD** [comment] 2019-11-06 00:54
All .command is not work

**Comment by RestudyXD** [comment] 2019-11-06 00:55
Air jump not work

**Comment by carloslol109** [comment] 2019-11-06 01:04
I thought horion wasn’t available on 1.13

**Comment by Zelqx** [comment] 2019-11-06 11:05
It’s beta, you gotta pay to join

**Comment by Zelqx** [comment] 2019-11-07 10:35
@richardletshacks thank you for removing the gamer font.

**Comment by NOcturnais** [comment] 2019-11-07 16:08
.give don't work on servers

**Comment by richardletshacks** [comment] 2019-11-07 16:09
> .give don't work on servers

Well if servers patched it, we can't do anything about it.

**Comment by NOcturnais** [comment] 2019-11-07 16:11
No they don't patched it it's work in 1.12.1 version but not in beta

**Comment by imfuckingtoasted** [comment] 2019-11-07 16:12
Yea .give works on 1.12.1 in mineplex

**Comment by NOcturnais** [comment] 2019-11-07 16:12
yeah

**Comment by NOcturnais** [comment] 2019-11-07 16:13
But not in 1.13

**Comment by imfuckingtoasted** [comment] 2019-11-07 16:14
Yea I downgraded the C R A F T to 1.12.1 because I use .give and .enchant on mineplex for my store in the community I made in survival

**Comment by richardletshacks** [comment] 2019-11-08 15:47
>  ESP Rainbow for everything instead of Mobs : Blue , Players: LGBT

This isn't even a bug

**Comment by imfuckingtoasted** [comment] 2019-11-08 15:58
Not a big but can you make esp colors changeable between a few options like how you’d bind a key to something

**Comment by imfuckingtoasted** [comment] 2019-11-08 15:59
Not a bug***

**Comment by richardletshacks** [comment] 2019-11-08 16:43
Also whats the problem with `.bind glide`? Works for me.

**Comment by imfuckingtoasted** [comment] 2019-11-08 16:45
Nothing it was a request because you can’t see mobs that well when grey thru the wall for like care packages on survival games so I was wondering if you could possibly make it an option For the player to change that to like red or green with a command like .bind

**Comment by imfuckingtoasted** [comment] 2019-11-08 16:48
Sorry for any grammatical errors I’m pretty lit

**Comment by Oinkoz** [comment] 2019-11-09 00:46
horion just doesnt inject in 1.13

**Comment by NOcturnais** [comment] 2019-11-09 00:48
Oinkoz Learn how to compile a project

**Comment by Oinkoz** [comment] 2019-11-09 00:48
what does that mean?

**Comment by Oinkoz** [comment] 2019-11-09 00:49
like how do i do that

**Comment by NOcturnais** [comment] 2019-11-09 00:49
https://github.com/horionclient/Horion/wiki/Installation-&-setup

**Comment by NOcturnais** [comment] 2019-11-09 00:50
And search the dll in the folder where you downloaded the sources

**Comment by NOcturnais** [comment] 2019-11-09 00:51
In x64/Debug

**Comment by NOcturnais** [comment] 2019-11-09 00:52
https://anonfile.com/33R4p0Abn6/Horion_1.13_BETA_dll

**Comment by NOcturnais** [comment] 2019-11-09 00:52
Here's the link ;)

**Comment by Oinkoz** [comment] 2019-11-09 01:05
so i just have to download that and inject it using the injector?

**Comment by Oinkoz** [comment] 2019-11-09 01:13
if thats the case then it doesnt work

**Comment by xPixel2k** [comment] 2019-11-09 01:23
You have to install visual studio then install the desktop developing for c++ pack, once that's done Horion should work

**Comment by richardletshacks** [comment] 2019-11-09 08:00
All important bugs have been fixed

**Comment by Ohtim1** [comment] 2019-11-09 16:33
> https://github.com/horionclient/Horion/wiki/Installation-&-setup

it doesn't work on mine! please help and I had installed https://aka.ms/vs/16/release/vc_redist.x64.exe.

**Comment by Xderar** [comment] 2019-11-09 20:42
Critical hit doesn't work

**Comment by Xderar** [comment] 2019-11-09 20:43
Step only makes you step 2 blocks even if set to the maximum setting

**Comment by Xderar** [comment] 2019-11-09 20:46
Fastladder doesn't work

**Comment by Zelqx** [comment] 2019-11-09 21:17
@Xderar fastladder does work.

**Comment by Xderar** [comment] 2019-11-09 22:47
Mobaura or mobesp acts like xp dropped from some mobs is an enemy and attacks it until it's picked up or out of range

**Comment by Zelqx** [comment] 2019-11-10 00:31
why is .give not important :l its our only way of getting things

**Comment by SurvirvorHRG** [comment] 2019-11-10 00:32
because you can use the item id to get wood or other stuff if name doesn't work

**Comment by Zelqx** [comment] 2019-11-10 00:50
name is more prefered on my side. and ID takes longer to get. but ok

**Comment by Xderar** [comment] 2019-11-10 03:00
agreed ^

**Comment by SonThanh2k5** [comment] 2019-11-10 03:17
> Whenever I inject my game just crashes what is that?

you need to wait the loading screen is done and inject

**Comment by Zelqx** [comment] 2019-11-10 03:18
Could you stop saying your crashing? Seriously. get the beta version if you dont want to crash. :(

**Comment by akmvihfan** [comment] 2019-11-10 03:25
Jesus Infomation:
Walk On The "Weather" ,like a jesus
Not  weather ,Water

**Comment by richardletshacks** [comment] 2019-11-10 21:31
> Criticals has problems with NoFall - You'll kinda randomly get fall damage and die from it
I think we should try to achieve criticals by another way than setting the onGround value to true. Isn't there some Criticals Packet that we could send when we hit a player?

**Comment by Hellohi3654** [comment] 2019-11-11 07:13
doing .give blue_ice gives you gold ingots

**Comment by OhBoyItsGrelAgain** [comment] 2019-11-11 08:21
Can confirm. Issue occurs on latest Horion Beta release.

**Comment by louandyDiazYT39** [comment] 2019-11-11 12:44
I'm haven't a problem injection, it doesn't work on 1.13.0?

**Comment by richardletshacks** [comment] 2019-11-16 08:10
> When clicking on module on the new array list, it doesnt turn off the module
not a bug

**Comment by DylanVidzOnYT** [comment] 2019-11-28 06:42
fix your font

**Closed** 2020-09-04 18:31 UTC
Labels: bug
