### ISSUE TITLE
Airjump Still not working

### ISSUE THREAD

**Issue by LVGG911** [horionclient/Horion#371] opened 2020-10-24 23:21 UTC
I don't want to be annoying but it say's its fixed 10 hour's ago but it still isn't fixed cause i can't walk that smooth and still can't make 5 jump's the way you can see that it's the old airjump is to hold space cause you keep jumping in the air if its working

➡️ https://www.youtube.com/watch?v=3c1EhtQdta4 ⬅️
Still have the video so u can see that u walk diffrent when i jump 😄 i hope yall can fix this cause i love this client

**Comment by GodGamer029** [comment] 2020-10-25 10:50
you should not make open issues for the dev version if you aren't using the dev version
duplicate of #353

**Closed by GodGamer029** 2020-10-25 10:50 UTC
Labels: bug
